FROM n8nio/n8n:latest
# Post v1.0:
USER root
RUN npm install -g n8n-nodes-clicksend && npm install -g n8n-nodes-clickuplookup && npm install -g n8n-nodes-browserless && npm install -g n8n-nodes-meilisearch
USER node